print('Hello World!')
print('Whta is your name?')
myName = input()
print('It is good to meet you, ' + myName)
print('the Length of your name is:')
print(len(myName))
print('what is your age?')
Myage = input()
print('You will be ' + str(int(Myage) + 1) + ' in one year.')